// Generated by scripts/dist/gen-distro-manifest.ts from dsh-compat/contract/extensions.yml and
// dsh.upstream.json. Do not edit; rerun the script after changing either file.
import type { LyteboatDistroExtension } from '@lyteboat/contracts'

/** The dsh release the kernel was imported from. */
export const DSH_BASE = '0.1.7-rc.2'

/** Every kernel extension this build carries. */
export const DISTRO_EXTENSIONS: readonly LyteboatDistroExtension[] = Object.freeze([
  { id: 'agent-loop-intake', package: '@deepseek-ai/dsh-agent-loop', kind: 'event', since: 'lyteboat on dsh 0.1.7-rc.1 (carried from the lyteboat driver fork since M2)' },
  { id: 'agent-loop-pre-assemble', package: '@deepseek-ai/dsh-agent-loop', kind: 'event', since: 'lyteboat on dsh 0.1.7-rc.1 (carried from the lyteboat driver fork since M2)' },
  { id: 'session-append-ignorable', package: '@deepseek-ai/dsh-session', kind: 'api-option', since: 'lyteboat on dsh 0.1.7-rc.1' },
])
